spring:
  docker:
    compose:
      file: Backend/compose.yaml
  security:
    user:
      name: user
      password: user
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: myuser
    password: secret
    url: jdbc:mariadb://localhost:3306/mydatabase
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

